### ISSUE TITLE
Import / export

### ISSUE THREAD

**Issue by gabfl** [urld/passmgr#1]
Hi David,

Your project is very interesting, I would love to use it.

Do you have a solution to import passwords? IMO most people already have tens or hundred of passwords and providing this feature would greatly help.

Same for exporting.

Thanks!

**Comment by urld** [comment]
It should be possible to add a feature which imports a set of passwords from a json file or some other format.

But im not sure if this would be very helpful. How would you create such a file, passmgr can read from?

**Comment by gabfl** [comment]
A lot of password managers have import/export tool (see a list for example at https://www.passwordstore.org/).

Formatting a file to a custom Json format will be a bit time consuming but a lot less than inputing tens/hundred of passwords by hand.

IMO you would get a lot more users if you gave them a tool to import an existing list of passwords. Most people interested in this product are already using some sort of password management tool.

**Comment by urld** [comment]
Im thinking about adding something like a `-batch` or `-import` flag to load multiple entries from a simple plaintext or json formatted file.
Generating input for this option based on exported data of other password managers should then be trivial, and contributions are always welcome.

**Comment by gabfl** [comment]
I think its a great idea

**Comment by urld** [comment]
I just added "import from json".
Have a look at the example at [passmgr doc](https://godoc.org/github.com/urld/passmgr/cmd/passmgr).

**Comment by gabfl** [comment]
👍 awesome

**Comment by sergeevabc** [comment]
Err… And what about export?

**Comment by urld** [comment]
@sergeevabc If you have a feature request please open a new issue and describe your usecase in detail.

**Comment by sergeevabc** [comment]
Everything is already described in the very first message up above.
Request mentioned two interlinked features, but you delivered just one, the half.
Import allows to use the existing volume of passwords, export allows to walk away painlessly.
Actually I see you made no commits since 1 Jul 2017, perhaps it’s better to say the app is [abandoned][1]?

[1]: https://en.wikipedia.org/wiki/Abandonware

**Comment by urld** [comment]
It's not abandoned, it just fulfills my own needs for now. It's actually the only reason I wrote it. I don't need an export option.

So, if you need one please open a new issue and state exactly what you want.
That includes: what is your exact usecase, which format would be useful to you.

I could just add an export option, but I doubt it would be useful to any non technical user, since the output needs to be converted to a format known by a different password manager.
